### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by idevelopr** [ZingyTomato/GaanaPy#3]
How reliable is the Live API domain https://api.nikomusic.tk/ ?

It is obviously not an official domain of Gaana.

**Comment by ZingyTomato** [comment]
> How reliable is the Live API domain https://api.nikomusic.tk/ ?
> 
> It is obviously not an official domain of Gaana.

I'm just self hosting it so that people can try it out. You can deploy it for yourself in docker : https://github.com/ZingyTomato/GaanaPy#-docker-deployment

Sadly this API is not popular enough for somebody with a dedicated vps/server to host it on.

**Comment by idevelopr** [comment]
Thank you for the response.

How often do you think the song url decryption mechanism might change? As in key or IV etc.
Even if it changes, do we have a way to decrypt again? I'm also curious how you were able to figure out the current decipher. Do you mind talking about it?

Additionally, can you document actual Gaana endpoints somewhere, please?

**Comment by idevelopr** [comment]
I see. Hopefully, the cipher won't change. 

And, I did notice high-quality stream and it's really cool that the audio is loud and clear.

Please ignore documenting endpoints. I guess I can actually get them from your code. The reason I am looking for Ganna endpoints is that in case your server is down. So, I can directly hit Gaana. Another reason to hit Gaana directly is that when I use your API, the response is taking too long. I am not certain if it is because of my VPN or something, but Gaana does respond back very quickly.

You can close this issue unless you have anything else to add.

**Comment by ZingyTomato** [comment]
@idevelopr You don't have to use my instance, you can just run it locally https://github.com/ZingyTomato/GaanaPy#-local-development.
